[build]
  functions = "functions/"

[template.environment]
  BASE_URL = "Base URL e.g. https://example.com"
  AWS_LAMBDA_JS_RUNTIME = "Node runtime (enter \"nodejs12.x\")"

[[redirects]]
  from = "/print/*"
  to = "/.netlify/functions/print/:splat"
  status = 200

[[redirects]]
  from = "/screenshot/*"
  to = "/.netlify/functions/screenshot/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/screenshot/:splat"
  status = 301
